services:
  moncip-lis:
    container_name: moncip-lis
    build:
      context: .
      target: dev
    env_file:
      - .env
      - .env.local
    volumes:
      - ./:/app
      - pnpm-store:/pnpm/store
    ports:
      - 3000:3000

  db:
    image: postgres:17
    shm_size: 128mb
    environment:
      POSTGRES_USER: moncip_lis
      POSTGRES_PASSWORD: moncip_lis

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  pnpm-store:
