export const PERMISSIONS = {
  PATIENT_READ: "PATIENT:READ",
  PATIENT_LINK: "PATIENT:LINK",
  PATIENT_CREATE: "PATIENT:CREATE",
  PATIENT_UPDATE: "PATIENT:UPDATE",
  PATIENT_DELETE: "PATIENT:DELETE",
  PATIENT_UNDELETE: "PATIENT:UNDELETE",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
